import java.time.LocalDate;

/**
 * Encapsulates expense data.
 * This class now works with an ID generated by the database.
 */
class Expense {
    private int id;
    private double amount;
    private String category;
    private String description;
    private LocalDate date;

    /**
     * Constructor for creating a new expense, with the ID to be assigned by the database.
     */
    public Expense(double amount, String category, String description, LocalDate date) {
        this.amount = amount;
        this.category = category;
        this.description = description;
        this.date = date;
    }

    /**
     * Constructor for creating an expense object from a database record, which already has an ID.
     */
    public Expense(int id, double amount, String category, String description, LocalDate date) {
        this.id = id;
        this.amount = amount;
        this.category = category;
        this.description = description;
        this.date = date;
    }

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }
    public double getAmount() { return amount; }
    public String getCategory() { return category; }
    public String getDescription() { return description; }
    public LocalDate getDate() { return date; }

    @Override
    public String toString() {
        return String.format("ID: %d, Amount: $%.2f, Category: %s, Description: %s, Date: %s",
                id, amount, category, description, date);
    }
}
